spring:
  application:
    name: tbilisi-dog-map
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tbilisi_dog_map}
    username: ${DB_USERNAME:my_user}
    password: ${DB_PASSWORD:my_pass}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${PORT:8080}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}

app:
  cors:
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS:https://*.github.io}
